language: node_js
node_js:
  - 6
  - 8
services:
  - redis-server
script:
  - cp default.config.json config.json
  - npm run test
after_success:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
