language: node_js
node_js:
  - 6
  - 8
  - node
services:
  - redis-server
script:
  - cp default.config.json config.json
  - make test
  - make test-cov
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
