language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "io.js"
sudo: false
services:
  - redis-server
test:
  - cp default.config.json config.json
  - npm test
after_succes:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
