env:
  - CXX=g++-4.8
language: node_js
node_js:
  - 4
  - 6
  - node
sudo: false
services:
  - redis-server
script:
  - cp default.config.json config.json
  - make test
  - make test-cov
addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - gcc-4.8
       - g++-4.8
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
