name: Main CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      REDIS_ENV: redis-server
    strategy:
      matrix:
        node: [ '14']
    services:
      redis-server:
        image: redis
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: cp default.config.json config.json
      - run: npm test
      - run: npm run coverage
        if: matrix.node == 14
      - name: Coveralls
        if: matrix.node == 14
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
